<a href="https://colab.research.google.com/github/in-Sinergy/TAREA-2/blob/main/Tarea2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##importamos y leemos el database
import pandas as pd
UNLink = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSPVJIoDhupNyUpYD65FSHt6kMmF_KaxE2RD6CV1FOMP4vVw7WfKQMqpqo0ieD9vhMAmYP1NpBmw0od/pub?gid=658985149&single=true&output=csv"
HumanDvp = pd.read_csv(UNLink)
HumanDvp

,Back,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 1. Arreglo de la tabla de datos

In [ ]:
#podemos notar que los nombres de las columnas son incorrectos y los valores aparecen como N/A
#entre la tercera y cuarta fila, encontramos los nombres correctos de las columnas. Cambiamos los correspondientes.
HumanDvp.columns.to_list()

['Back',
 'Table 1. Human Development Index and its components',
 'Unnamed: 2',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14']

In [ ]:
change={'Back':"HDI_rank", 'Table 1. Human Development Index and its components': 'Country', 'Unnamed: 2': "HDI", 'Unnamed: 4': "life_exp", 'Unnamed: 6': "school_exp",'Unnamed: 10': "GNI", 'Unnamed: 12': "GNI_min_HDI"}
HumanDvp.rename(columns=change,inplace=True)
HumanDvp

,HDI_rank,Country,HDI,Unnamed: 3,life_exp,Unnamed: 5,school_exp,Unnamed: 7,Unnamed: 8,Unnamed: 9,GNI,Unnamed: 11,GNI_min_HDI,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
4,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Nos deshacemos de las columnas restantes que se mantuvieron sin nombrar
keep=['HDI_rank', 'Country','HDI', 'life_exp', 'school_exp', 'GNI', 'GNI_min_HDI']
dontKeep = set(HumanDvp.columns.to_list())-set(keep)
HumanDvp = HumanDvp.drop(columns=dontKeep)
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,SDG3,SDG4.3,SDG8.5,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
4,HDI rank,Country,Value,(years),(years),(2017 PPP $),NaN
...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

In [ ]:
#una vez manejado el tema de las columnas, se deben eliminar las filas iniciales y finales sobrantes
#de acuerdo con el database en excel, las primeras 8 filas no son parte de la data
HumanDvp = HumanDvp.drop(range(0,7))
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,Switzerland,962,84.0,16.5,"66,933",5
8,2,Norway,961,83.2,18.2,"64,660",6
9,3,Iceland,959,82.7,19.2,"55,782",11
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,"62,607",6
11,5,Australia,951,84.5,21.1,"49,238",18
...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

In [ ]:
#al hacer este primer cambio, podemos notar que los datos, anteriormente N/A, ahora sí aparecen.
#trabajando con las columnas finales, buscamos eliminar todos los datos de texto que aparecen al final
HumanDvp.tail(70)
#estos son todos los que debemos eliminar

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,Human development groups,NaN,NaN,NaN,NaN,NaN
208,NaN,Very high human development,896,78.5,16.5,"43,752",—
209,NaN,High human development,754,74.7,14.2,"15,167",—
210,NaN,Medium human development,636,67.4,11.9,"6,353",—
...,...,...,...,...,...,...,...
271,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN
272,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN
273,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN
275,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN

In [ ]:
HumanDvp = HumanDvp.drop(range(206,276))
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,Switzerland,962,84.0,16.5,"66,933",5
8,2,Norway,961,83.2,18.2,"64,660",6
9,3,Iceland,959,82.7,19.2,"55,782",11
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,"62,607",6
11,5,Australia,951,84.5,21.1,"49,238",18
...,...,...,...,...,...,...,...
201,NaN,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN
202,NaN,Korea (Democratic People's Rep. of),..,73.3,10.8,..,..
203,NaN,Monaco,..,85.9,..,..,..
204,NaN,Nauru,..,63.6,11.7,"17,73",..
205,NaN,Somalia,..,55.3,..,"1,018",..

In [ ]:
#Los últimos países del database serán eliminados por practicidad
HumanDvp = HumanDvp.drop(range(201,206))
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,Switzerland,962,84.0,16.5,"66,933",5
8,2,Norway,961,83.2,18.2,"64,660",6
9,3,Iceland,959,82.7,19.2,"55,782",11
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,"62,607",6
11,5,Australia,951,84.5,21.1,"49,238",18
...,...,...,...,...,...,...,...
196,187,Burundi,426,61.7,10.7,732,4
197,188,Central African Republic,404,53.9,8.0,966,1
198,189,Niger,400,61.6,7.0,"1,240",-3
199,190,Chad,394,52.5,8.0,"1,364",-7
200,191,South Sudan,385,55.0,5.5,768,-1

In [ ]:
#Podría parecer que ya se ha eliminado todo, pero si revisamos el tamaño de la tabla:
HumanDvp.shape
#observamos que hay 3 celdas de más donde solo nos deberían quedar 191 países

(194, 7)

In [ ]:
#el problema son los subtítulos de orden entre países, que serán eliminados
missing_values = HumanDvp.isnull().sum()
missing_values

HDI_rank       3
Country        0
HDI            3
life_exp       3
school_exp     3
GNI            3
GNI_min_HDI    3
dtype: int64

In [ ]:
HumanDvp = HumanDvp.dropna()

In [ ]:
missing_values = HumanDvp.isnull().sum()
missing_values

HDI_rank       0
Country        0
HDI            0
life_exp       0
school_exp     0
GNI            0
GNI_min_HDI    0
dtype: int64

In [ ]:
#Ya tenemos la database lista para empezar con la limpieza y formateo
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,Switzerland,962,84.0,16.5,"66,933",5
8,2,Norway,961,83.2,18.2,"64,660",6
9,3,Iceland,959,82.7,19.2,"55,782",11
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,"62,607",6
11,5,Australia,951,84.5,21.1,"49,238",18
...,...,...,...,...,...,...,...
196,187,Burundi,426,61.7,10.7,732,4
197,188,Central African Republic,404,53.9,8.0,966,1
198,189,Niger,400,61.6,7.0,"1,240",-3
199,190,Chad,394,52.5,8.0,"1,364",-7
200,191,South Sudan,385,55.0,5.5,768,-1

# 2. Limpieza de datos

In [ ]:
#Verificamos qué tipos de datos hay en cada columna
HumanDvp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 7 to 200
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDI_rank     191 non-null    object
 1   Country      191 non-null    object
 2   HDI          191 non-null    object
 3   life_exp     191 non-null    object
 4   school_exp   191 non-null    object
 5   GNI          191 non-null    object
 6   GNI_min_HDI  191 non-null    object
dtypes: object(7)
memory usage: 11.9+ KB

In [ ]:
#todas las columnas excepto Country deberían contener datos numéricos
#Verificamos presencia de caracteres no numéricos
set(HumanDvp.GNI.str.extractall('(\W)').loc[:,0].to_list())-set('.')

{','}

In [ ]:
#eliminamos las comas
HumanDvp['GNI']=HumanDvp.GNI.str.replace(",",'')
HumanDvp

<ipython-input-180-18ed1930082c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  HumanDvp['GNI']=HumanDvp.GNI.str.replace(",",'')

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,Switzerland,962,84.0,16.5,66933,5
8,2,Norway,961,83.2,18.2,64660,6
9,3,Iceland,959,82.7,19.2,55782,11
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,62607,6
11,5,Australia,951,84.5,21.1,49238,18
...,...,...,...,...,...,...,...
196,187,Burundi,426,61.7,10.7,732,4
197,188,Central African Republic,404,53.9,8.0,966,1
198,189,Niger,400,61.6,7.0,1240,-3
199,190,Chad,394,52.5,8.0,1364,-7
200,191,South Sudan,385,55.0,5.5,768,-1

In [ ]:
set(HumanDvp.GNI.str.extractall('(\W)').loc[:,0].to_list())-set('.')

set()

In [ ]:
#quitamos los espacios que pueda haber
objectCols=HumanDvp.select_dtypes(include=['object']).columns
objectCols

Index(['HDI_rank', 'Country', 'HDI', 'life_exp', 'school_exp', 'GNI',
       'GNI_min_HDI'],
      dtype='object')

In [ ]:
HumanDvp=HumanDvp.loc[:,objectCols].apply(lambda col:col.str.strip())
HumanDvp
#con esto, podemos asumir limpio el database

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,Switzerland,962,84.0,16.5,66933,5
8,2,Norway,961,83.2,18.2,64660,6
9,3,Iceland,959,82.7,19.2,55782,11
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,62607,6
11,5,Australia,951,84.5,21.1,49238,18
...,...,...,...,...,...,...,...
196,187,Burundi,426,61.7,10.7,732,4
197,188,Central African Republic,404,53.9,8.0,966,1
198,189,Niger,400,61.6,7.0,1240,-3
199,190,Chad,394,52.5,8.0,1364,-7
200,191,South Sudan,385,55.0,5.5,768,-1

# 3. Formateo del database

In [ ]:
#revisamos el tipo de dato presente en cada columna
HumanDvp.info()
#todas excepto Country deberían ser numéricas

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 7 to 200
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDI_rank     191 non-null    object
 1   Country      191 non-null    object
 2   HDI          191 non-null    object
 3   life_exp     191 non-null    object
 4   school_exp   191 non-null    object
 5   GNI          191 non-null    object
 6   GNI_min_HDI  191 non-null    object
dtypes: object(7)
memory usage: 11.9+ KB

In [ ]:
#seleccionamos las columnas a convertir
objCol = ['Country']
numCol = list(set(HumanDvp.columns.to_list())- set(objCol))
numCol

['HDI_rank', 'GNI', 'GNI_min_HDI', 'HDI', 'life_exp', 'school_exp']

In [ ]:
#definimos una función para convertir los datos de obj a numéricos
def objToNum (xNum):
    import re
    xNum=pd.to_numeric(xNum)
    return xNum

In [ ]:
#aplicamos la función a todas las columnas
HumanDvp[numCol]= HumanDvp.loc[:, numCol].applymap(objToNum)
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,Switzerland,962,84.0,16.5,66933,5
8,2,Norway,961,83.2,18.2,64660,6
9,3,Iceland,959,82.7,19.2,55782,11
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,62607,6
11,5,Australia,951,84.5,21.1,49238,18
...,...,...,...,...,...,...,...
196,187,Burundi,426,61.7,10.7,732,4
197,188,Central African Republic,404,53.9,8.0,966,1
198,189,Niger,400,61.6,7.0,1240,-3
199,190,Chad,394,52.5,8.0,1364,-7
200,191,South Sudan,385,55.0,5.5,768,-1

In [ ]:
#verificamos que haya cambiado el tipo de data
HumanDvp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 7 to 200
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDI_rank     191 non-null    int64
 1   Country      191 non-null    object
 2   HDI          191 non-null    int64
 3   life_exp     191 non-null    float64
 4   school_exp   191 non-null    float64
 5   GNI          191 non-null    int64
 6   GNI_min_HDI  191 non-null    int64
dtypes: float64(2), int64(4), object(1)
memory usage: 11.9+ KB

In [ ]:
#finalmente, trabajamos con la columna de texto (Country)
#buscamos duplicados
HumanDvp[HumanDvp.duplicated(subset='Country')]

Empty DataFrame
Columns: [HDI_rank, Country, HDI, life_exp, school_exp, GNI, GNI_min_HDI]
Index: []

In [ ]:
#ahora revisamos caracteres diferentes de letras
HumanDvp[HumanDvp.Country.str.contains(r"[^\w\s]")]

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
10,4,"Hong Kong, China (SAR)",952,85.5,17.3,62607,6
26,19,Korea (Republic of),925,83.7,16.5,44501,9
83,76,Iran (Islamic Republic of),774,73.9,14.6,13001,15
88,80,Moldova (Republic of),767,68.8,14.4,14875,-1
113,106,"Palestine, State of",715,73.5,13.4,6583,21
126,118,Bolivia (Plurinational State of),692,63.6,14.9,8111,0
128,120,Venezuela (Bolivarian Republic of),691,70.6,12.8,4811,20
142,134,Micronesia (Federated States of),628,70.7,11.5,3696,22
148,140,Lao People's Democratic Republic,607,68.1,10.1,7700,-18
149,140,Timor-Leste,607,67.7,12.6,4461,7
152,144,Eswatini (Kingdom of),597,57.1,13.7,7679,-21
167,159,Côte d'Ivoire,550,58.6,10.7,5217,-22
169,160,Tanzania (United Republic of),549,66.2,9.2,2664,7
186,177,Guinea-Bissau,483,59.7,10.6,1908,0
188,179,Congo (Democratic Republic of the),479,59.2,9.8,1076,9

In [ ]:
#buscamos acentos
HumanDvp[HumanDvp.Country.str.contains(r"\w*[\u00C0-\u01DA']\w*")]

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
54,48,Türkiye,838,76.0,18.3,31033,-3
148,140,Lao People's Democratic Republic,607,68.1,10.1,7700,-18
167,159,Côte d'Ivoire,550,58.6,10.7,5217,-22

In [ ]:
pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 5.7 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.8

In [ ]:
#convertimos los símbolos encontrados a su equivalente en ascii
from unidecode import unidecode
HumanDvp['Country']=HumanDvp.Country.apply(unidecode)

In [ ]:
#por practicidad, se colocarán todos los nombres de países en mayúsculas
HumanDvp['Country']=HumanDvp.Country.str.upper()
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,SWITZERLAND,962,84.0,16.5,66933,5
8,2,NORWAY,961,83.2,18.2,64660,6
9,3,ICELAND,959,82.7,19.2,55782,11
10,4,"HONG KONG, CHINA (SAR)",952,85.5,17.3,62607,6
11,5,AUSTRALIA,951,84.5,21.1,49238,18
...,...,...,...,...,...,...,...
196,187,BURUNDI,426,61.7,10.7,732,4
197,188,CENTRAL AFRICAN REPUBLIC,404,53.9,8.0,966,1
198,189,NIGER,400,61.6,7.0,1240,-3
199,190,CHAD,394,52.5,8.0,1364,-7
200,191,SOUTH SUDAN,385,55.0,5.5,768,-1

In [ ]:
#finalmente, revisamos los paréntesis
HumanDvp[HumanDvp.Country.str.contains(r"[(][^)]*[)]")]

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
10,4,"HONG KONG, CHINA (SAR)",952,85.5,17.3,62607,6
26,19,KOREA (REPUBLIC OF),925,83.7,16.5,44501,9
83,76,IRAN (ISLAMIC REPUBLIC OF),774,73.9,14.6,13001,15
88,80,MOLDOVA (REPUBLIC OF),767,68.8,14.4,14875,-1
126,118,BOLIVIA (PLURINATIONAL STATE OF),692,63.6,14.9,8111,0
128,120,VENEZUELA (BOLIVARIAN REPUBLIC OF),691,70.6,12.8,4811,20
142,134,MICRONESIA (FEDERATED STATES OF),628,70.7,11.5,3696,22
152,144,ESWATINI (KINGDOM OF),597,57.1,13.7,7679,-21
169,160,TANZANIA (UNITED REPUBLIC OF),549,66.2,9.2,2664,7
188,179,CONGO (DEMOCRATIC REPUBLIC OF THE),479,59.2,9.8,1076,9

In [ ]:
#como solo se encuentran especificaciones, se puede prescindir de ellas
HumanDvp['Country']=HumanDvp.Country.str.replace(pat=r"\(.*\)",repl="", regex=True)

# 4. Resultados

In [ ]:
#Con esto tenemos el resultado final
HumanDvp

,HDI_rank,Country,HDI,life_exp,school_exp,GNI,GNI_min_HDI
7,1,SWITZERLAND,962,84.0,16.5,66933,5
8,2,NORWAY,961,83.2,18.2,64660,6
9,3,ICELAND,959,82.7,19.2,55782,11
10,4,"HONG KONG, CHINA",952,85.5,17.3,62607,6
11,5,AUSTRALIA,951,84.5,21.1,49238,18
...,...,...,...,...,...,...,...
196,187,BURUNDI,426,61.7,10.7,732,4
197,188,CENTRAL AFRICAN REPUBLIC,404,53.9,8.0,966,1
198,189,NIGER,400,61.6,7.0,1240,-3
199,190,CHAD,394,52.5,8.0,1364,-7
200,191,SOUTH SUDAN,385,55.0,5.5,768,-1

In [ ]:
HumanDvp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191 entries, 7 to 200
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   HDI_rank     191 non-null    int64
 1   Country      191 non-null    object
 2   HDI          191 non-null    int64
 3   life_exp     191 non-null    float64
 4   school_exp   191 non-null    float64
 5   GNI          191 non-null    int64
 6   GNI_min_HDI  191 non-null    int64
dtypes: float64(2), int64(4), object(1)
memory usage: 11.9+ KB